FROM openshift/origin-release:golang-1.14 AS build
COPY . /go/src/velero-plugin-for-csi
WORKDIR /go/src/velero-plugin-for-csi
RUN CGO_ENABLED=0 GOOS=linux go build -v -o /go/bin/velero-plugin-for-csi -mod=mod .


FROM registry.access.redhat.com/ubi8-minimal
RUN mkdir /plugins
COPY --from=build /go/bin/velero-plugin-for-csi /plugins/
USER nobody:nobody
ENTRYPOINT ["/bin/bash", "-c", "cp /plugins/* /target/."]
